import { describe, expect, it } from "vitest";

import { CodexCliProvider, type CodexCliToolBroker } from "./index.js";

describe("CodexCliProvider", () => {
  it("turns installed-Codex output into a reviewable changeset", async () => {
    const provider = new CodexCliProvider({
      runCodexExec: () =>
        Promise.resolve({
          targetFilePath: "main.tex",
          summary: "Add document end",
          afterContents:
            "\\documentclass{article}\n\\begin{document}\nHello\n\\end{document}\n",
          notes: "Generated by fake Codex runner"
        })
    });
    const broker: CodexCliToolBroker = {
      readFile: () =>
        Promise.resolve({
          path: "main.tex",
          contents: "\\documentclass{article}\n\\begin{document}\nHello\n",
          mtimeMs: 1
        }),
      searchProject: () => Promise.resolve([]),
      proposePatch: (_filePath, _beforeContents, afterContents, summary) =>
        Promise.resolve({
          id: "changeset-1",
          projectRoot: "/tmp/project",
          filePath: "main.tex",
          summary,
          patch: afterContents,
          status: "proposed",
          baseSnapshotId: "snapshot-1",
          createdAt: "2026-06-08T00:00:00.000Z",
          updatedAt: "2026-06-08T00:00:00.000Z"
        })
    };

    const result = await provider.startSession(
      {
        providerId: "openai-codex",
        mode: "apply-with-review",
        projectRoot: "/tmp/project",
        prompt: "Fix the compile error",
        activeFilePath: "main.tex",
        mainFilePath: "main.tex",
        compiler: "pdflatex"
      },
      broker
    );

    expect(result.status).toBe("awaiting-approval");
    expect(result.changeset?.summary).toBe("Add document end");
    expect(result.events.some((event) => event.type === "approval")).toBe(true);
    expect(
      result.events.some(
        (event) => event.type === "tool-call" && event.toolName === "codex-exec"
      )
    ).toBe(true);
  });
});
