import { describe, expect, it } from "vitest";

import {
  ClaudeProvider,
  parseClaudePatchResponseFromCli,
  parseClaudePatchResponse,
  type ClaudeCodeToolBroker
} from "./index.js";

describe("ClaudeProvider", () => {
  it("reports needs-auth when the Claude Code CLI is logged out", async () => {
    const provider = new ClaudeProvider({
      getCliAuthStatus: () => Promise.resolve({ loggedIn: false })
    });

    await expect(provider.getAuthStatus()).resolves.toMatchObject({
      providerId: "anthropic-claude",
      state: "needs-auth"
    });
  });

  it("turns Claude output into a reviewable changeset", async () => {
    const provider = new ClaudeProvider({
      getCliAuthStatus: () => Promise.resolve({ loggedIn: true }),
      runClaudeCode: () =>
        Promise.resolve({
          targetFilePath: "main.tex",
          summary: "Add document end",
          afterContents:
            "\\documentclass{article}\n\\begin{document}\nHello\n\\end{document}\n",
          notes: "Generated by fake Claude runner"
        })
    });
    const broker: ClaudeCodeToolBroker = {
      readFile: () =>
        Promise.resolve({
          path: "main.tex",
          contents: "\\documentclass{article}\n\\begin{document}\nHello\n",
          mtimeMs: 1
        }),
      searchProject: () => Promise.resolve([]),
      proposePatch: (_filePath, _beforeContents, afterContents, summary) =>
        Promise.resolve({
          id: "changeset-1",
          projectRoot: "/tmp/project",
          filePath: "main.tex",
          summary,
          patch: afterContents,
          status: "proposed",
          baseSnapshotId: "snapshot-1",
          createdAt: "2026-06-08T00:00:00.000Z",
          updatedAt: "2026-06-08T00:00:00.000Z"
        })
    };

    const result = await provider.startSession(
      {
        providerId: "anthropic-claude",
        mode: "apply-with-review",
        projectRoot: "/tmp/project",
        prompt: "Fix the compile error",
        activeFilePath: "main.tex",
        mainFilePath: "main.tex",
        compiler: "pdflatex"
      },
      broker
    );

    expect(result.status).toBe("awaiting-approval");
    expect(result.changeset?.summary).toBe("Add document end");
    expect(result.events.some((event) => event.type === "approval")).toBe(true);
    expect(
      result.events.some(
        (event) => event.type === "tool-call" && event.toolName === "claude-code"
      )
    ).toBe(true);
  });

  it("parses Claude Code structured output", () => {
    expect(
      parseClaudePatchResponseFromCli(
        JSON.stringify({
          structured_output: {
            targetFilePath: "main.tex",
            summary: "Fix",
            afterContents: "ok",
            notes: "done"
          }
        })
      )
    ).toEqual({
      targetFilePath: "main.tex",
      summary: "Fix",
      afterContents: "ok",
      notes: "done"
    });
  });

  it("parses fenced JSON responses", () => {
    expect(
      parseClaudePatchResponse(`\`\`\`json
{"targetFilePath":"main.tex","summary":"Fix","afterContents":"ok","notes":"done"}
\`\`\``)
    ).toEqual({
      targetFilePath: "main.tex",
      summary: "Fix",
      afterContents: "ok",
      notes: "done"
    });
  });
});
